# Site settings
title: Develop Freedom
header-img: img/home-bg.jpg
email: me@shubhamchaudhary.in
description: "Develop Freedom - Blog by Shubham Chaudhary"
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://shubham.chaudhary.xyz" # the base hostname & protocol for your site
author_name: Shubham Chaudhary
twitter_username: ylogx
github_username: ylogx
facebook_username: ylogx
feedburner_email_subscribe_link: "https://feedburner.google.com/fb/a/mailverify?uri=chaudhary_xyz&amp;loc=en_US"
feedburner_rss_link: "http://feeds.feedburner.com/chaudhary_xyz"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
feed:
  categories:
  - kde
  - ml
  - akademy
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", ".idea"]
#plugins: [jekyll-paginate, jekyll-feed]  # sudo gem install --verbose <name>
plugins:
  - jekyll-paginate
  - jekyll-feed
  #- amp-jekyll
  #- jekyll-sitemap
