# Site settings
title: Develop Freedom
header-img: img/home-bg.jpg
email: me@shubhamchaudhary.in
description: "Develop Freedom - Blog by Shubham Chaudhary"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://developfreedom.org" # the base hostname & protocol for your site
twitter_username: ChaudharySimply
github_username:  shubhamchaudhary
facebook_username:  ShubhamChaudhary.in

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
