# Site settings
title: Develop Freedom
header-img: img/home-bg.jpg
email: me@shubhamchaudhary.in
description: "Develop Freedom - Blog by Shubham Chaudhary"
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://shubham.chaudhary.xyz" # the base hostname & protocol for your site
twitter_username: ylogx
github_username: ylogx
facebook_username: ylogx

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate]  # sudo gem install --verbose <name>
